basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is the API documentation for Argo.
  title: Argo API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Get the health status of the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - health
swagger: "2.0"
